### PR TITLE
Fix let

### LINKED ISSUE #58: trouble with let
```
def simple : {
  (A : univ) (a : A) -> A
} = {
  \A a =>
  let b : A = a in
  b
}

normalize simple
```
raises ```Internal error (Failed to normalize): do_sub_out```.

I failed to track down the reason. (The same thing happens on the pathcoe or fhcom branches btw.)

### PR DESCRIPTION
**Pull request by jonsterling**
Resolves #58

### CODE REVIEW

File: src/lib/Refiner.ml [hunk 1]
```diff
@@ -605,12 +605,15 @@ struct
...
+    fun goal ->
     let* tdef, tp_def = tac_def in
+    EM.with_pp @@ fun ppenv ->
     let* vdef = EM.lift_ev @@ Nbe.eval tdef in
-    T.let_ tp_def vdef nm_x @@ fun x ->
-    let+ tbdy = tac_bdy x tp in
-    S.Let (tdef, tbdy)
+    let* tbdy =
+      T.abstract (D.Sub (tp_def, Cof_tl.top, D.const_tm_clo vdef)) nm_x @@ fun var ->
+      tac_bdy var goal
```
Comment (jonsterling) [inline src/lib/Refiner.ml:614]: In fact, I think that this is not quite right. (It works but it isn't yet right).

Comment (jonsterling) [reply src/lib/Refiner.ml:614]: The problem is that it seems like we can't actually push in the boundary condition for this style of rule. I need to look at it on paper before I resume. But I'm way too busy today.

Comment (jonsterling) [reply src/lib/Refiner.ml:614]: Oh wait, I think it's ok because the binding has the singleton type!

File: src/lib/Refiner.ml [hunk 2]
```diff
@@ -605,12 +605,15 @@ struct
     index ix
 
   let let_ tac_def (nm_x, (tac_bdy : T.var -> T.bchk_tac)) : T.bchk_tac =
-    fun tp ->
+    fun goal ->
     let* tdef, tp_def = tac_def in
+    EM.with_pp @@ fun ppenv ->
```
Comment (jonsterling) [inline src/lib/Refiner.ml:610]: ooos, guess i should delete this
